### ISSUE TITLE
error while attempting to start service

### ISSUE THREAD

**Issue by oasec1** [godaddy/procfilter#1]
![master windows 7 pro n 32bit-2016-07-30-11-08-45](https://cloud.githubusercontent.com/assets/4145850/17271335/bfea59cc-5646-11e6-8273-a4c4730dc2c5.png)

Windows version professional 7 sp3

reboot had the same result on restart.  installation used the right click option of runas administrator

Thanks
Robert

**Comment by ewil** [comment]
I had forgotten about this issue and should've included info about it in the README. Unpatched Windows 7 systems require the hotfix at [Microsoft Security Advisory 3033929](https://technet.microsoft.com/en-us/library/security/3033929) in order to verify SHA-2 (SHA256) digital signatures. Current driver signing certificates can only sign using SHA256 so we unfortunately can't sign with SHA-1 to be backwards compatible. More details about Microsoft's deprecation of SHA-1 can be found at [Windows Enforcement of Authenticode Code Signing and Timestamping](http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx).

If this fix works for you let me know so I can move to close the issue by updating the project README and making that 577 dialog box clearer. Thank you for the bug report, we appreciate it!

**Comment by oasec1** [comment]
I'm having a problem finding the file to download from MS. The  site link
doesn't download the specific OS file. Feel free to close the issue until I
can get the  correct file from MS.

Thanks
Robert

**Comment by cycad** [comment]
The links to the patches should be at the above security advisory link under the "Affected Software" section. If you're able to apply the patch and still have problems, don't hesitate to open another issue and we'll get it figured out. Thanks Robert!

**Comment by ewil** [comment]
The links to the patches should be at the above security advisory link under the "Affected Software" section. If you're able to apply the patch and still have problems, don't hesitate to open another issue and we'll get it figured out. Thanks Robert!

**Comment by oasec1** [comment]
Just a quick update The patches fixed the issues.

Regards
Robert

**Comment by ewil** [comment]
Great! Thanks for the update!
