### ISSUE TITLE
Still being updated?

### ISSUE THREAD

**Issue by ion-storm** [godaddy/procfilter#6]
Just checking in to see if this is still being maintained, I see the Yara rules are a bit old.

**Comment by ewil** [comment]
The intent of the included YARA rules are to provide examples to get users started -- they aren't meant as a comprehensive ruleset. It may be possible to use large rulesets from other YARA rule repositories but including one with ProcFilter is beyond the scope of what I can support.

The primary use case is if you have a homogeneous environment and need to mitigate malicious activity within. A large hosting environment, for example, might see automated activity associated with a malware campaign and denying execution of their specific tools can be valuable in the window between detection and 3rd party vendor response. Or as a way to log their command-line activity to better understand the attacker's TTP. A secondary use case is an analyst needs access to process, thread, and DLL load events in userspace. For example, this can be used to detect and suspend inter-process thread creation (process injection) or to help with examining malicious memory space without involving a debugger via the unpack plugin.

If you have other use cases for ProcFilter I'm interested in hearing them. I'll respond to any bugs or feature requests submitted as issues. I've held off on new releases hoping https://github.com/VirusTotal/yara/issues/510 would be addressed since it has performance implications for ProcFilter but it may be time to find a work around.
