### ISSUE TITLE
prerequisites for running this project with VS 2015

### ISSUE THREAD

**Issue by hdi-amiri** [godaddy/procfilter#9]
I was wondering what are the prerequisites for running this project? I cloned the repository and opened the solution with VS15 but lots of errors appeared during the compilation.

**Comment by hdi-amiri** [comment]
here is the screen shot of visual studio output:
![image](https://user-images.githubusercontent.com/10879511/36344831-3c2877fa-1435-11e8-84cc-a798de7c306f.png)
and the project directory:
![image](https://user-images.githubusercontent.com/10879511/36344835-4e57dc4a-1435-11e8-81ec-fea2232c9052.png)

**Comment by ewil** [comment]
Looks like your VS Solution can't find the path to Lua -- "lua.h" and "lua.hpp" should be right in the Lua directory as they are part of the standard Lua package:

```
X:\lua-5.3.2>dir lua.h*
 Volume in drive X is Shared Folders
 Volume Serial Number is 0000-0000

 Directory of X:\lua-5.3.2

11/13/15  10:18 AM            14,825 lua.h
12/22/04  05:53 PM               191 lua.hpp
               2 File(s)         15,016 bytes
               0 Dir(s)  35,281,805,312 bytes free

X:\lua-5.3.2>
```

Does adjusting the Include Directories setting in the project fix this for you?

**Comment by hdi-amiri** [comment]
Yes thanks very much, the problem was that the original `lua` package that I downloaded had all the header files in "src" folder, I moved them up and everything compiled smoothly, there was a problem for getting the `git2.lib` file which I compiled it manually myself, but I am still unclear about debug and release `.lib` files.

another issue I encountered was for driver signing which by using a test signature was gone, I had issue with `Inf2Cat`, Some strange errors I got which I resolved it by using `/uselocaltime`.

I needed to have the `git2.dll` in the folder where the final `procfilter.exe` exist, I did it manually and copied it in the Debug folder, am I doing it right? or the build process should do it automatically?

**Comment by ewil** [comment]
Nice! Sounds like you made some good progress.

For libgit2, their license states you cannot redistribute the binary unless it's part of an installer. The implications of this are that it can't live in this repository. There's a README with more info on it and how to build it at https://github.com/godaddy/procfilter/tree/master/deps/libgit2 but you can use either Debug or Release mode builds of it. I recommend Release mode since your intent is likely to test ProcFilter and not the libgit2 component. The README also says what to do with `git2.dll`. If that doesn't work let me know and I'll update it.

For driver signing it's annoying but you'll have to either have your own certificate or self-sign it. It's a Microsoft limitation. Unless you're editing the driver code what you can do is just copy the driver file from the signed installer into your project and just never build the driver, that way it'll pull the signed copy every time.

With this taken care of you should be able to build the project and build the installers. The signing portion won't work unless you have your own certificate. So you can remove the 'sign_installers.bat' and 'sign_binaries.bat' invocations from `build.bat` and then invoking it should work.
